// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiemgijifyiowqirctfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZW1naWppZnlpb3dxaXJjdGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzU1MTgsImV4cCI6MjA2MzY1MTUxOH0.Kr9_jpVrpCltH_RQEMzC5HDaorPyxMHE_7jFX0XAnIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);